version: '3.9'

services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql_lab
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql