spring:
  application:
    name: msclientes

  datasource:
    url: jdbc:mysql://localhost:3306/healthflow_clientes
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }
    prefer-ip-address: true
    ip-address: 127.0.0.1
