spring:
  application:
    name: msclientes

  datasource:
    url: jdbc:mysql://localhost:3306/healthflow_clientes
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true


server:
  port: 8081
